spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.serialization.StringDeserializer

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.serialization.StringSerializer
      value-serializer: org.apache.kafka.serialization.StringSerializer